# Generated by Django 5.2.6 on 2025-09-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_date_of_birth_user_email_user_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recepients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email_pass',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='user',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
