# Generated by Django 5.2.6 on 2025-09-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_recepients_user_email_host_user_email_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepients',
            name='email_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
