# Generated by Django 5.2.6 on 2025-09-17 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_recepients_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepients',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
