# Generated by Django 5.2.6 on 2025-09-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_helps_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images/'),
        ),
    ]
