# Generated by Django 5.2.6 on 2026-05-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipient',
        ),
        migrations.AlterModelOptions(
            name='recepients',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='recepients',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recepients',
            name='email_address',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
