# Generated by Django 5.2.6 on 2025-09-20 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_helps_help'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
