# Generated by Django 5.2.6 on 2025-09-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_emailtemplates_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplates',
            name='template_name',
            field=models.CharField(max_length=50),
        ),
    ]
