# Generated by Django 5.2.6 on 2025-09-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='user',
        ),
    ]
