# Generated by Django 5.2.6 on 2025-09-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_login_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='last_name',
        ),
    ]
