# Generated by Django 5.2.6 on 2025-09-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_recepients_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepients',
            name='notes',
        ),
    ]
