# Generated by Django 5.2.6 on 2025-09-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_helps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='helps',
            new_name='help',
        ),
    ]
